name: Test & Deploy | develop

on:
  push:
    branches:
      - "develop"
jobs:
  check_deploy_macos:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.konan*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - run: 'echo "$PGP_KEY_PRIVATE" | base64 --decode > private.key'
        shell: bash
        env:
          PGP_KEY_PRIVATE: ${{secrets.S_PGP_KEY_PRIVATE}}
      - run: './gradlew --no-daemon publishDevelop'
        env:
          ORG_GRADLE_PROJECT_devBuildNumber: ${{github.run_number}}
          ORG_GRADLE_PROJECT_pearxRepoUsername: ${{secrets.S_PEARX_REPO_USERNAME}}
          ORG_GRADLE_PROJECT_pearxRepoPassword: ${{secrets.S_PEARX_REPO_PASSWORD}}
          ORG_GRADLE_PROJECT_signing.keyId: ${{secrets.S_PGP_KEY_PUBID}}
          ORG_GRADLE_PROJECT_signing.password: ${{secrets.S_PGP_KEY_PASSWORD}}
          ORG_GRADLE_PROJECT_signing.secretKeyRingFile: private.key
          ORG_GRADLE_PROJECT_multigradle.publishHostExclusivesOnly: true
  check_deploy_windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.konan*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - run: 'echo "$PGP_KEY_PRIVATE" | base64 --decode > private.key'
        shell: bash
        env:
          PGP_KEY_PRIVATE: ${{secrets.S_PGP_KEY_PRIVATE}}
      - run: 'CALL gradlew.bat --no-daemon publishDevelop'
        shell: cmd
        env:
          ORG_GRADLE_PROJECT_devBuildNumber: ${{github.run_number}}
          ORG_GRADLE_PROJECT_pearxRepoUsername: ${{secrets.S_PEARX_REPO_USERNAME}}
          ORG_GRADLE_PROJECT_pearxRepoPassword: ${{secrets.S_PEARX_REPO_PASSWORD}}
          ORG_GRADLE_PROJECT_signing.keyId: ${{secrets.S_PGP_KEY_PUBID}}
          ORG_GRADLE_PROJECT_signing.password: ${{secrets.S_PGP_KEY_PASSWORD}}
          ORG_GRADLE_PROJECT_signing.secretKeyRingFile: private.key
          ORG_GRADLE_PROJECT_multigradle.publishHostExclusivesOnly: true
  check_deploy_linux:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.konan*') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - run: 'echo "$PGP_KEY_PRIVATE" | base64 --decode > private.key'
        shell: bash
        env:
          PGP_KEY_PRIVATE: ${{secrets.S_PGP_KEY_PRIVATE}}
      - run: './gradlew --no-daemon publishDevelop'
        env:
          ORG_GRADLE_PROJECT_devBuildNumber: ${{github.run_number}}
          ORG_GRADLE_PROJECT_pearxRepoUsername: ${{secrets.S_PEARX_REPO_USERNAME}}
          ORG_GRADLE_PROJECT_pearxRepoPassword: ${{secrets.S_PEARX_REPO_PASSWORD}}
          ORG_GRADLE_PROJECT_signing.keyId: ${{secrets.S_PGP_KEY_PUBID}}
          ORG_GRADLE_PROJECT_signing.password: ${{secrets.S_PGP_KEY_PASSWORD}}
          ORG_GRADLE_PROJECT_signing.secretKeyRingFile: private.key